In [4]:
import pandas as pd

In [34]:
data = pd.read_csv("data/combine_Data.csv")
data

,STATE_ID,METRIC_ID,MAC_ID,CORRECTED_ADDRESS,504_COMPLIANCE,REASON_CD,GENERIC_CD,METRIC_COUNT,REPORTING_DATE
0,AK,5-2W,NaN,N,N,NaN,NaN,51,7/6/2018
1,AR,5-2W,NaN,N,N,NaN,NaN,256,7/6/2018
2,AZ,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
3,CA,5-2W,NaN,N,N,NaN,NaN,451,7/6/2018
4,CA,5-2W,NaN,Y,N,NaN,NaN,6,7/6/2018
5,CO,5-2W,NaN,N,N,NaN,NaN,3,7/6/2018
6,CT,5-2W,NaN,N,N,NaN,NaN,3,7/6/2018
7,DC,5-2W,NaN,N,N,NaN,NaN,7,7/6/2018
8,DC,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
9,DE,5-2W,NaN,N,N,NaN,NaN,21,7/6/2018
10,FL,5-2W,NaN,N,N,NaN,NaN,12,7/6/2018
11,GA,5-2W,NaN,N,N,NaN,NaN,6,7/6/2018
12,GU,5-2W,NaN,N,N,NaN,NaN,2,7/6/2018
13,HI,5-2W,NaN,N,N,NaN,NaN,21,7/6/2018
14,ID,5-2W,NaN,N,N,NaN,NaN,1,7/6/2018
15,IL,5-2W,NaN,N,N,NaN,NaN,11,7/6/2018
16,IN,5-2W,NaN,N,N,NaN,NaN,4,7/6/2018
17,KS,5-2W,NaN,N,N,NaN,NaN,4,7/6/2018
18,KY,5-2W,NaN,N,N,NaN,NaN,5,7/6/2018
19,LA,5-2W,NaN,N,N,NaN,NaN,5,7/6/2018
20,MA,5-2W,NaN,N,N,NaN,NaN,6,7/6/2018
21,MD,5-2W,NaN,N,N,NaN,NaN,133,7/6/2018
22,MD,5-2W,NaN,Y,N,NaN,NaN,6,7/6/2018
23,MI,5-2W,NaN,N,N,NaN,NaN,9,7/6/2018
24,MN,5-2W,NaN,N,N,NaN,NaN,2,7/6/2018
25,MO,5-2W,NaN,N,N,NaN,NaN,3,7/6/2018
26,MS,5-2W,NaN,N,N,NaN,NaN,3,7/6/2018
27,MT,5-2W,NaN,N,N,NaN,NaN,1,7/6/2018
28,NC,5-2W,NaN,N,N,NaN,NaN,8,7/6/2018
29,ND,5-2W,NaN,N,N,NaN,NaN,1,7/6/2018
...,...,...,...,...,...,...,...,...,...
114,NY,5-2W,NaN,Y,N,NaN,NaN,2,7/6/2018
115,OH,5-2W,NaN,N,N,NaN,NaN,41,7/6/2018
116,OH,5-2W,NaN,Y,N,NaN,NaN,2,7/6/2018
117,OK,5-2W,NaN,N,N,NaN,NaN,269,7/6/2018
118,OK,5-2W,NaN,Y,N,NaN,NaN,7,7/6/2018
119,OR,5-2W,NaN,N,N,NaN,NaN,441,7/6/2018
120,OR,5-2W,NaN,Y,N,NaN,NaN,11,7/6/2018
121,PA,5-2W,NaN,N,N,NaN,NaN,1453,7/6/2018
122,PA,5-2W,NaN,Y,N,NaN,NaN,29,7/6/2018
123,PR,5-2W,NaN,N,N,NaN,NaN,17,7/6/2018
124,RI,5-2W,NaN,N,N,NaN,NaN,5,7/6/2018
125,SC,5-2W,NaN,N,N,NaN,NaN,15,7/6/2018
126,SC,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
127,SD,5-2W,NaN,N,N,NaN,NaN,68,7/6/2018
128,SD,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
129,TN,5-2W,NaN,N,N,NaN,NaN,15,7/6/2018
130,TN,5-2W,NaN,Y,N,NaN,NaN,2,7/6/2018
131,TX,5-2W,NaN,N,N,NaN,NaN,76,7/6/2018
132,TX,5-2W,NaN,Y,N,NaN,NaN,3,7/6/2018
133,UT,5-2W,NaN,N,N,NaN,NaN,5,7/6/2018
134,VA,5-2W,NaN,N,N,NaN,NaN,884,7/6/2018
135,VA,5-2W,NaN,Y,N,NaN,NaN,24,7/6/2018
136,VT,5-2W,NaN,N,N,NaN,NaN,4,7/6/2018
137,WA,5-2W,NaN,N,N,NaN,NaN,23,7/6/2018
138,WA,5-2W,NaN,Y,N,NaN,NaN,2,7/6/2018
139,WI,5-2W,NaN,N,N,NaN,NaN,473,7/6/2018
140,WI,5-2W,NaN,Y,N,NaN,NaN,9,7/6/2018
141,WV,5-2W,NaN,N,N,NaN,NaN,233,7/6/2018
142,WV,5-2W,NaN,Y,N,NaN,NaN,4,7/6/2018
143,WY,5-2W,NaN,N,N,NaN,NaN,1,7/6/2018

In [65]:
cols = list(data.columns.values)
d2 = pd.DataFrame(columns = cols)
d2

Empty DataFrame
Columns: [STATE_ID, METRIC_ID, MAC_ID, CORRECTED_ADDRESS, 504_COMPLIANCE, REASON_CD, GENERIC_CD, METRIC_COUNT, REPORTING_DATE]
Index: []

In [21]:
d2 = d2.append(data.iloc[0])

In [22]:
d2.drop(0, inplace=True)

In [66]:
d2

Empty DataFrame
Columns: [STATE_ID, METRIC_ID, MAC_ID, CORRECTED_ADDRESS, 504_COMPLIANCE, REASON_CD, GENERIC_CD, METRIC_COUNT, REPORTING_DATE]
Index: []

In [68]:
for i in range(len(data)):
    match = False
    row1 = list(data.iloc[i])
    for j in range(len(data)):
        if i == j:
            continue
        else:
            row2 = list(data.iloc[j])
            rw2 = data.iloc[j]
            if row1[0] == row2[0] and row1[3] == row2[3] and row1[4] == row2[4] and row1[8] == row2[8]:
                row3 = row1
                met = row1[7] + row2[7]
                row3[7] = met
                d2.loc[i] = row3
                match = True
                break
    if match == False:
        d2.loc[i] = row1

In [70]:
d2.drop_duplicates(subset=None, keep='first', inplace=True)

In [71]:
d2

,STATE_ID,METRIC_ID,MAC_ID,CORRECTED_ADDRESS,504_COMPLIANCE,REASON_CD,GENERIC_CD,METRIC_COUNT,REPORTING_DATE
0,AK,5-2W,NaN,N,N,NaN,NaN,51,7/6/2018
1,AR,5-2W,NaN,N,N,NaN,NaN,256,7/6/2018
2,AZ,5-2W,NaN,Y,N,NaN,NaN,4,7/6/2018
3,CA,5-2W,NaN,N,N,NaN,NaN,3938,7/6/2018
4,CA,5-2W,NaN,Y,N,NaN,NaN,74,7/6/2018
5,CO,5-2W,NaN,N,N,NaN,NaN,24,7/6/2018
6,CT,5-2W,NaN,N,N,NaN,NaN,19,7/6/2018
7,DC,5-2W,NaN,N,N,NaN,NaN,49,7/6/2018
8,DC,5-2W,NaN,Y,N,NaN,NaN,3,7/6/2018
9,DE,5-2W,NaN,N,N,NaN,NaN,150,7/6/2018
10,FL,5-2W,NaN,N,N,NaN,NaN,69,7/6/2018
11,GA,5-2W,NaN,N,N,NaN,NaN,35,7/6/2018
12,GU,5-2W,NaN,N,N,NaN,NaN,11,7/6/2018
13,HI,5-2W,NaN,N,N,NaN,NaN,176,7/6/2018
14,ID,5-2W,NaN,N,N,NaN,NaN,8,7/6/2018
15,IL,5-2W,NaN,N,N,NaN,NaN,813,7/6/2018
16,IN,5-2W,NaN,N,N,NaN,NaN,498,7/6/2018
17,KS,5-2W,NaN,N,N,NaN,NaN,221,7/6/2018
18,KY,5-2W,NaN,N,N,NaN,NaN,20,7/6/2018
19,LA,5-2W,NaN,N,N,NaN,NaN,24,7/6/2018
20,MA,5-2W,NaN,N,N,NaN,NaN,36,7/6/2018
21,MD,5-2W,NaN,N,N,NaN,NaN,701,7/6/2018
22,MD,5-2W,NaN,Y,N,NaN,NaN,28,7/6/2018
23,MI,5-2W,NaN,N,N,NaN,NaN,45,7/6/2018
24,MN,5-2W,NaN,N,N,NaN,NaN,391,7/6/2018
25,MO,5-2W,NaN,N,N,NaN,NaN,24,7/6/2018
26,MS,5-2W,NaN,N,N,NaN,NaN,9,7/6/2018
27,MT,5-2W,NaN,N,N,NaN,NaN,5,7/6/2018
28,NC,5-2W,NaN,N,N,NaN,NaN,40,7/6/2018
29,ND,5-2W,NaN,N,N,NaN,NaN,51,7/6/2018
...,...,...,...,...,...,...,...,...,...
74,IA,5-2W,NaN,N,N,NaN,NaN,260,7/6/2018
75,IA,5-2W,NaN,Y,N,NaN,NaN,6,7/6/2018
77,ID,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
79,IL,5-2W,NaN,Y,N,NaN,NaN,22,7/6/2018
81,IN,5-2W,NaN,Y,N,NaN,NaN,8,7/6/2018
83,KS,5-2W,NaN,Y,N,NaN,NaN,7,7/6/2018
87,MA,5-2W,NaN,Y,N,NaN,NaN,2,7/6/2018
90,ME,5-2W,NaN,N,N,NaN,NaN,5,7/6/2018
91,ME,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
93,MI,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
95,MN,5-2W,NaN,Y,N,NaN,NaN,16,7/6/2018
97,MO,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
98,MP,5-2W,NaN,N,N,NaN,NaN,2,7/6/2018
103,ND,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
105,NE,5-2W,NaN,Y,N,NaN,NaN,4,7/6/2018
108,NJ,5-2W,NaN,Y,N,NaN,NaN,3,7/6/2018
110,NM,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
112,NV,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
116,OH,5-2W,NaN,Y,N,NaN,NaN,2,7/6/2018
118,OK,5-2W,NaN,Y,N,NaN,NaN,7,7/6/2018
123,PR,5-2W,NaN,N,N,NaN,NaN,17,7/6/2018
126,SC,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
128,SD,5-2W,NaN,Y,N,NaN,NaN,1,7/6/2018
132,TX,5-2W,NaN,Y,N,NaN,NaN,3,7/6/2018
133,UT,5-2W,NaN,N,N,NaN,NaN,5,7/6/2018
136,VT,5-2W,NaN,N,N,NaN,NaN,4,7/6/2018
138,WA,5-2W,NaN,Y,N,NaN,NaN,2,7/6/2018
140,WI,5-2W,NaN,Y,N,NaN,NaN,9,7/6/2018
142,WV,5-2W,NaN,Y,N,NaN,NaN,4,7/6/2018
143,WY,5-2W,NaN,N,N,NaN,NaN,1,7/6/2018

In [72]:
d2.to_csv("datas.csv")